spring:
  application:
    name: server

server:
  port: 8080

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: AIzaSyDw27Wc_oVlK58dVbkQ_0LLDhmy950Ky1g